#!/usr/bin/env bash
# .env generation — secure secrets, master password prompt

gen_hex() { openssl rand -hex "${1:-32}"; }
gen_b64() { openssl rand -base64 "${1:-48}" | tr -d '\n/+='; }

# Returns 0 if password meets SQL Server policy
# Policy: min 8 chars, uppercase, lowercase, digit, special char
_meets_mssql_policy() {
    local p="$1"
    [[ ${#p} -ge 8 ]] \
        && [[ "$p" =~ [A-Z] ]] \
        && [[ "$p" =~ [a-z] ]] \
        && [[ "$p" =~ [0-9] ]] \
        && [[ "$p" =~ [^a-zA-Z0-9] ]]
}

prompt_master_password() {
    log_step "Master password"
    log_info "Same password used for PostgreSQL, MongoDB and SQL Server."
    echo
    printf "  ${GRAY}Requirements (SQL Server policy):${RESET}\n"
    printf "  ${GRAY}  • Minimum 8 characters${RESET}\n"
    printf "  ${GRAY}  • At least one uppercase letter  (A-Z)${RESET}\n"
    printf "  ${GRAY}  • At least one lowercase letter  (a-z)${RESET}\n"
    printf "  ${GRAY}  • At least one digit             (0-9)${RESET}\n"
    printf "  ${GRAY}  • At least one special character (!@#\$%%)${RESET}\n"
    echo

    local p1 p2
    while true; do
        read -rsp "  ${BOLD}Enter master password:${RESET}   " p1; echo
        if ! _meets_mssql_policy "$p1"; then
            log_warn "Password doesn't meet requirements. Try again."
            echo
            continue
        fi
        read -rsp "  ${BOLD}Confirm password:${RESET}        " p2; echo
        if [ "$p1" != "$p2" ]; then
            log_warn "Passwords don't match. Try again."
            echo
            continue
        fi
        break
    done

    MASTER_PASSWORD="$p1"
}

generate_env() {
    log_step "Generating secure environment"

    local fastapi_key jwt_secret
    fastapi_key=$(gen_hex 32)
    jwt_secret=$(gen_b64 64)

    spinner_start "Generating secrets..."
    sleep 0.4
    spinner_stop

    cat > .env <<EOF
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── SQL Server ──────────────────────────────────────────
MSSQL_SA_PASSWORD=${MASTER_PASSWORD}
MSSQL_DB=QualityDMS

# ── PostgreSQL ──────────────────────────────────────────
POSTGRES_DB=PublicDMS
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${MASTER_PASSWORD}

# ── MongoDB ─────────────────────────────────────────────
MONGO_USER=mongoadmin
MONGO_PASSWORD=${MASTER_PASSWORD}

# ── FastAPI ─────────────────────────────────────────────
FASTAPI_API_KEY=${fastapi_key}
FASTAPI_URL=http://fastapi:8000

# ── JWT / Internal ──────────────────────────────────────
JWT_SECRET=${jwt_secret}
EOF

    log_ok ".env generated"
    log_ok "SQL Server, PostgreSQL, MongoDB  ${GRAY}→ master password${RESET}"
    log_ok "FastAPI API key  ${GRAY}(256-bit random)${RESET}"
    log_ok "JWT secret       ${GRAY}(384-bit base64)${RESET}"
}

handle_existing_env() {
    [ "${SKIP_ENV:-false}" = true ] && { log_info "Using existing .env (--skip-env)"; return 0; }
    [ ! -f .env ] && return 0

    if [ "${FORCE:-false}" = true ]; then
        log_warn ".env exists — overwriting (--force)"
        return 0
    fi

    echo
    log_warn ".env already exists."
    local answer
    read -rp "  Overwrite? [y/N]: " answer
    if [[ "${answer,,}" == "y" ]]; then
        log_info "Overwriting .env"
    else
        log_info "Keeping existing .env"
        SKIP_ENV=true
    fi
}
