#!/usr/bin/env bash
# .env generation — secure secrets, master password prompt

gen_hex() { openssl rand -hex "${1:-32}"; }
gen_b64() { openssl rand -base64 "${1:-48}" | tr -d '\n/+='; }

# Returns 0 if password meets SQL Server policy
_meets_mssql_policy() {
    local p="$1"
    [[ ${#p} -ge 8 ]] \
        && [[ "$p" =~ [A-Z] ]] \
        && [[ "$p" =~ [a-z] ]] \
        && [[ "$p" =~ [0-9] ]] \
        && [[ "$p" =~ [^a-zA-Z0-9] ]]
}

prompt_seed_mode() {
    log_step "Modo de instalación"
    echo
    printf "  ${WHITE}[1]  Sandbox${RESET}     — 10,000 documentos generados automáticamente\n"
    printf "       ${GRAY}Sistema listo para demo desde el primer arranque.${RESET}\n"
    echo
    printf "  ${WHITE}[2]  Development${RESET} — Sistema limpio, sin documentos\n"
    printf "       ${GRAY}Solo usuarios, roles y configuración base.${RESET}\n"
    echo

    local choice
    while true; do
        read -rp "  Opción [1/2]: " choice
        case "$choice" in
            1) SEED_MODE="sandbox"; break ;;
            2) SEED_MODE="dev";     break ;;
            *) log_warn "Escribe 1 o 2." ;;
        esac
    done

    local label
    label=$( [ "$SEED_MODE" = "sandbox" ] && echo "Sandbox (10,000 docs)" || echo "Development (limpio)" )
    log_ok "Modo: $label"
    echo
}

prompt_master_password() {
    log_step "Master password"
    log_info "Same password used for PostgreSQL, MongoDB and SQL Server."
    echo
    printf "  ${GRAY}Requirements (SQL Server policy):${RESET}\n"
    printf "  ${GRAY}  • Minimum 8 characters${RESET}\n"
    printf "  ${GRAY}  • At least one uppercase letter  (A-Z)${RESET}\n"
    printf "  ${GRAY}  • At least one lowercase letter  (a-z)${RESET}\n"
    printf "  ${GRAY}  • At least one digit             (0-9)${RESET}\n"
    printf "  ${GRAY}  • At least one special character (!@#\$%%)${RESET}\n"
    echo

    local p1 p2
    while true; do
        read -rsp "  ${BOLD}Enter master password:${RESET}   " p1; echo
        if ! _meets_mssql_policy "$p1"; then
            log_warn "Password doesn't meet requirements. Try again."
            echo
            continue
        fi
        read -rsp "  ${BOLD}Confirm password:${RESET}        " p2; echo
        if [ "$p1" != "$p2" ]; then
            log_warn "Passwords don't match. Try again."
            echo
            continue
        fi
        break
    done

    MASTER_PASSWORD="$p1"
}

# Genera el .env raiz unico — consumido por los 3 docker-compose (--env-file .env).
# Equivalente al .env que produce setup.ps1. Las URLs cross-stack van inline en los compose.
_write_env_all() {
    local pass="$1" api_key="$2" jwt="$3"
    cat > .env <<EOF
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── SQL Server ──────────────────────────────────────────
MSSQL_SA_PASSWORD=${pass}
MSSQL_DB=QualityDMS

# ── PostgreSQL (cross-stack: fastapi/documents_sync -> dms_postgres) ─
POSTGRES_HOST=dms_postgres
POSTGRES_PORT=5432
POSTGRES_DB=PublicDMS
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${pass}

# ── MongoDB ─────────────────────────────────────────────
MONGO_USER=mongoadmin
MONGO_PASSWORD=${pass}

# ── Secretos compartidos ────────────────────────────────
FASTAPI_API_KEY=${api_key}
JWT_SECRET=${jwt}

# ── URLs cross-stack (container names sobre dms_backbone) ─
FASTAPI_URL=http://dms_fastapi:8000

# ── Seed mode: sandbox | dev | none ─────────────────────
DMS_SEED_MODE=${SEED_MODE:-dev}
EOF
}

# Genera .env.net para compose-net.yml
_write_env_net() {
    local pass="$1" api_key="$2" jwt="$3"
    cat > .env.net <<EOF
# Stack 1 — .NET + SQL Server
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── SQL Server ──────────────────────────────────────────
MSSQL_SA_PASSWORD=${pass}
MSSQL_DB=QualityDMS

# ── Shared secrets ──────────────────────────────────────
FASTAPI_API_KEY=${api_key}
JWT_SECRET=${jwt}

# ── Cross-stack URLs ────────────────────────────────────
PHP_WEBHOOK_URL=http://php
FASTAPI_WEBHOOK_URL=http://fastapi:8000

# ── Seed mode: sandbox | dev | none ─────────────────────
DMS_SEED_MODE=${SEED_MODE:-dev}
EOF
}

# Genera .env.php para compose-php.yml
_write_env_php() {
    local pass="$1" api_key="$2"
    cat > .env.php <<EOF
# Stack 2 — PHP + PostgreSQL + Nginx
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── PostgreSQL ──────────────────────────────────────────
POSTGRES_DB=PublicDMS
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${pass}

# ── Shared secrets ──────────────────────────────────────
FASTAPI_API_KEY=${api_key}

# ── Cross-stack URLs ────────────────────────────────────
FASTAPI_URL=http://fastapi:8000
DOTNET_API_URL=http://dotnet:8080
EOF
}

# Genera .env.indexer para compose-indexer.yml
_write_env_indexer() {
    local pass="$1" api_key="$2" jwt="$3"
    cat > .env.indexer <<EOF
# Stack 3 — FastAPI + MongoDB
# Generated by install.sh — $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to version control.

# ── MongoDB ─────────────────────────────────────────────
MONGO_USER=mongoadmin
MONGO_PASSWORD=${pass}

# ── Shared secrets ──────────────────────────────────────
FASTAPI_API_KEY=${api_key}
JWT_SECRET=${jwt}

# ── PostgreSQL cross-stack (documents_sync.py) ──────────
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=PublicDMS
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${pass}

# ── Cross-stack URLs ────────────────────────────────────
DOTNET_API_URL=http://dotnet:8080
EOF
}

generate_env() {
    log_step "Generating secure environment"

    local fastapi_key jwt_secret
    fastapi_key=$(gen_hex 32)
    jwt_secret=$(gen_b64 64)

    spinner_start "Generating secrets..."
    sleep 0.4
    spinner_stop

    # .env raiz unico — lo comparten los 3 stacks (--env-file .env).
    _write_env_all "$MASTER_PASSWORD" "$fastapi_key" "$jwt_secret"
    log_ok ".env generated  ${GRAY}(compartido por los 3 stacks)${RESET}"

    log_ok "FastAPI API key  ${GRAY}(256-bit random)${RESET}"
    log_ok "JWT secret       ${GRAY}(384-bit base64)${RESET}"
    echo
    log_warn "IMPORTANT: FASTAPI_API_KEY and JWT_SECRET must match across all stacks."
    log_info  "If stacks are on separate servers, copy the values manually."
}

handle_existing_env() {
    [ "${SKIP_ENV:-false}" = true ] && { log_info "Using existing .env (--skip-env)"; return 0; }

    # Modelo de .env unico compartido por los 3 stacks.
    local env_files=(".env")

    local any_exists=false
    for f in "${env_files[@]}"; do
        [ -f "$f" ] && any_exists=true && break
    done

    [ "$any_exists" = false ] && return 0

    if [ "${FORCE:-false}" = true ]; then
        log_warn "Env files exist — overwriting (--force)"
        return 0
    fi

    echo
    log_warn "Env file(s) already exist: ${env_files[*]}"
    local answer
    read -rp "  Overwrite? [y/N]: " answer
    if [[ "${answer,,}" == "y" ]]; then
        log_info "Overwriting env files"
    else
        log_info "Keeping existing env files"
        SKIP_ENV=true
    fi
}
